### ISSUE TITLE
Winning condition typo

### ISSUE THREAD

**Issue by YehorFeshchenko** [Mary1509/Renju#2]
https://github.com/Mary1509/Renju/blob/ea2997a1323a7789081a94fd1c647942cc43c193/main.py#L37

In `check_win`, the game checks for `count >= 5` which includes cases where there might be more than five stones, which, per the task's description, should not count as a win. I suppose the correct operator here should be `==`.

**Comment by Mary1509** [comment]
Thank you for identifying, the winning condition was updated as per requirements. Pull request updated.
https://github.com/Mary1509/Renju/blob/d4668971fdeb975cc6e120ba20cb1346958e0e41/main.py#L41
