### ISSUE TITLE
Player's representation readability improvement

### ISSUE THREAD

**Issue by YehorFeshchenko** [Mary1509/Renju#3]
https://github.com/Mary1509/Renju/blob/ea2997a1323a7789081a94fd1c647942cc43c193/main.py#L19-L29

The code frequently uses '1' and '2' to represent players. It would improve readability and maintainability to define these as named constants, e.g., BLACK = '1' and WHITE = '2'.

**Comment by Mary1509** [comment]
That's a good point, thanks.
The constants were added as for players and PR were updated.
https://github.com/Mary1509/Renju/blob/d4668971fdeb975cc6e120ba20cb1346958e0e41/main.py#L6-L8
https://github.com/Mary1509/Renju/blob/d4668971fdeb975cc6e120ba20cb1346958e0e41/main.py#L23-L33
